### ISSUE TITLE
Is ACCESS_WIFI_STATE used/required on android?

### ISSUE THREAD

**Issue by dpolivy** [quantcast/phonegap-measurement#6]
This plugin adds the `ACCESS_WIFI_STATE` permission to Android apps. But, when I look at the documentation for your Android SDK, it doesn't show that as a required (or even optional) permission. Is it necessary? Is it used?

If not, can the reference in `plugin.xml` be removed?

**Comment by SmithKevin** [comment]
You are correct, it is not required.   I will remove it from the plugin file.   Sorry about the confusion.

**Comment by dpolivy** [comment]
Thanks, @SmithKevin!
