### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by sarangan** [quantcast/phonegap-measurement#9]
Failed to install 'com.quantcast.phonegapplugin':Error: Expected plugin to have
ID "com.google.playservices" but got "cordova-plugin-googleplayservices".

cordova version is 5.3.3

**Comment by SmithKevin** [comment]
Hi @sarangan,   Thanks for the heads up.  Looks like something has recently changed with the google play services plugin.  I see a lot of other plugins are also having similar issues.   I will look into the fix now.

**Comment by dpolivy** [comment]
@SmithKevin Here's what I changed my plugin.xml to do get this to work consistently:

````
<dependency id="cordova-plugin-googleplayservices" url="https://github.com/floatinghotpot/google-play-services" commit="r19" />
````

**Comment by SmithKevin** [comment]
Fantastic.   I'll push these changes today.  @dpolivy Thanks for all the help.

**Comment by SmithKevin** [comment]
I have updated this.   Let me know if the issue remains.   Thanks
